# Change these first
owner: web-vlaanderen # Your GitHub username
repo: upptime # Your GitHub repository name

# Add your sites here
sites:
  - name: WEB Vlaanderen
    url: https://www.web.vlaanderen
  - name: Albert Vastgoed
    url: https://www.albert-vastgoed.be
  - name: Immo Acasa
    url: https://www.immoacasa.be
  - name: Aquis
    url: https://www.aquis.be
  - name: GetFullyLet
    url: https://www.getfullylet.com
  - name: Greenbuiling Projects
    url: https://www.greenbuildingprojects.be
  - name: ApartGent
    url: https://www.apartgent.be
  - name: Gimpex
    url: https://www.gimpex.be
  - name: CTWLK
    url: https://www.ctwlk.eu
  - name: Fleur Verbeek
    url: https://www.fleurverbeekdressage.com
  - name: Dierenarts Groot & Klein
    url: http://www.dapgrootenklein.be
  - name: Valkennest
    url: https://www.valkennest.be
  - name: David Van Hulle - Thuisverpleging
    url: https://www.davidvanhulle.be
    
assignees: # Users to assign downtime issues (optional)
  - webvlaanderen

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: upptime.web.vlaanderen
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://avatars3.githubusercontent.com/u/76779646?s=96&v=4
  name: Upptime WEB Vlaanderen
  introTitle: "WEB Vlaanderen **Upptime**"
  introMessage: **Real-time** loggen van websites
  navbar:
    - title: Status
      href: /
    - title: Website
      href: https://www.web.vlaanderen

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
