# Change these first
owner: web-vlaanderen # Your GitHub username
repo: upptime # Your GitHub repository name

# Add your sites here
sites:
  - name: WEB Vlaanderen
    url: https://www.web.vlaanderen
  - name: Coach WEB Vlaanderen
    url: https://coach.web.vlaanderen
  - name: Albert Vastgoed
    url: https://www.albert-vastgoed.be
  - name: Albert Boutique
    url: https://www.albert.boutique
  - name: Albert Vastgoed - Residentie Madison
    url: https://www.residentiemadison.be
  - name: Immo Acasa
    url: https://www.immoacasa.be
  - name: Aquis
    url: https://www.aquis.be
  - name: GetFullyLet
    url: https://www.getfullylet.com
  - name: Greenbuilding Projects
    url: https://www.greenbuildingprojects.be
  - name: ApartGent
    url: https://www.apartgent.be
  - name: Gimpex
    url: https://www.gimpex.be
  - name: CTWLK
    url: https://www.ctwlk.eu
  - name: Fleur Verbeek
    url: https://www.fleurverbeekdressage.com
  - name: Dierenarts Groot & Klein
    url: http://www.dapgrootenklein.be
  - name: Valkennest
    url: https://www.valkennest.be
  - name: David Van Hulle - Thuisverpleging
    url: https://www.davidvanhulle.be
  - name: Hydra Gent
    url: https://www.hydra-gent.be
  - name: Segway Brugge
    url: https://www.segway-brugge.be
  - name: Hippo Revue
    url: https://www.hipporevue.be
  - name: Hippo Koets
    url: https://koets.sightseeingbrugge.com
  - name: Equiphys
    url: https://www.equiphys.be
  - name: Furnished Apartments Gent
    url: https://www.furnishedapartmentsgent.be
  - name: YDS Hasselt
    url: https://www.ydshasselt.be
  - name: Tucasa
    url: https://www.tucasa.be
  - name: Mandus
    url: https://www.mandusdierickx.be
  - name: Lexington
    url: https://www.lexington.be
  - name: De Scheldepolder
    url: https://www.descheldepolder.be
  - name: Created Loppem
    url: https://www.createdloppem.be
  - name: Musicovideo
    url: https://www.musicovideo.com
  - name: NSLV
    url: https://www.nlsv.be
  - name: STKG
    url: https://www.stkg.be
  - name: VLS Horses
    url: https://www.vls-horses.be
    
    
assignees: # Users to assign downtime issues (optional)
  #- mslembro

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: upptime.web.vlaanderen
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://avatars3.githubusercontent.com/u/76779646?s=96&v=4
  name: Upptime WEB Vlaanderen
  introTitle: "WEB Vlaanderen **Upptime**"
  introMessage: "**Real-time** loggen van websites"
  navbar:
    - title: Status
      href: /
    - title: Website
      href: https://www.web.vlaanderen

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
